# Generated by Django 5.2.4 on 2025-07-24 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
